services:
  hexy-be:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      RL_ROOT: /vendor_rl
      CORS_ORIGINS: http://localhost:5173
    volumes:
      - ${VENDOR_RL_PATH}:/vendor_rl:ro
